/* ==========================================================================
   SHREE ASSOCIATES — reviews-data.js
   The actual client review dataset, kept separate from markup and logic so
   it can be updated independently (reviews.html renders this dynamically).
   Data is used exactly as supplied — no review added, removed, or reworded.
   ========================================================================== */

const reviews = [
    { name: "Asim Nisar Ahmed Gaibee", society: "Park Plaza Panvel", service: "Monthly Maintenance", rating: 5, review: "Nice service" },
    { name: "Rupesh Phale", society: "Manjulabai Complex", service: "Audit & Accounting", rating: 5, review: "Amazing services" },
    { name: "Punith Mahabal Shetty", society: "Public Sector", service: "Audit & Accounting", rating: 5, review: "" },
    { name: "Subhara Jyoti Das", society: "Aditya Heights CHS Ltd", service: "Audit & Accounting", rating: 5, review: "Excellent service coordinated by staff members Ms Shilpa and others" },
    { name: "Shankar Singh", society: "Tirupati Palace, Kamothe", service: "Property Registration", rating: 5, review: "Very good fast work" },
    { name: "Abdul Salam Khan", society: "Muneera Heights CHS Ltd", service: "Audit & Accounting", rating: 5, review: "Excellent service" },
    { name: "Nalanda Residency CHS Ltd", society: "Nalanda Residency CHS Ltd", service: "Audit & Accounting", rating: 5, review: "Good work" },
    { name: "Akshay Kokate", society: "Sai Siddhi Society Panvel", service: "Audit & Accounting", rating: 5, review: "" },
    { name: "Amol Arvind Shivram", society: "Sahyadri Co-op Hsg Society", service: "Audit & Accounting", rating: 5, review: "Good" },
    { name: "Vikas Korade", society: "Nirmala CHSL", service: "Legal Service", rating: 5, review: "Very cooperative nature and mastery in knowledge of cooperation and expert in law field." },
    { name: "Mohan Padya", society: "Sai Vrindavan Residency", service: "Conveyance / Deemed Conveyance", rating: 5, review: "" },
    { name: "Sunita Sunil Gajare", society: "Shree Associates", service: "Society Registration", rating: 5, review: "Good service" },
    { name: "Ashok Kumar Chattopadhyay", society: "Jayshree CHS Limited", service: "Audit & Accounting", rating: 5, review: "Very good" },
    { name: "M Mahalingam", society: "Platinum Liviano", service: "Audit & Accounting", rating: 5, review: "Excellent service given by you. Keep it up." },
    { name: "Nagesh Jadhav", society: "Vidyut CHS Ltd", service: "Conveyance / Deemed Conveyance", rating: 4, review: "Helpful person" },
    { name: "Vaibhav Shyam", society: "Shrushti CHS Ltd", service: "Legal Service", rating: 5, review: "Great approach to all govt authorities... work guarantee 100%" },
    { name: "Navnath Dattu Ganjave", society: "Shanti Sagar Co-op Housing Society", service: "Conveyance / Deemed Conveyance", rating: 5, review: "This achievement reflects your dedication, coordination, and commitment toward safeguarding the rights and interests of all society members." },
    { name: "Nagesh Dattatray Bhopi", society: "Manjulabai Complex", service: "Audit & Accounting", rating: 5, review: "Good" },
    { name: "Sawant Ankush", society: "Krishna Sai Darshan CHS", service: "Property Registration", rating: 5, review: "Very quick work & very good" },
    { name: "Yogesh Pawar", society: "Omega Residency", service: "Society Registration", rating: 5, review: "Service is good" },
    { name: "Babu Banshi Jadhav", society: "Shubhnil Shivam Housing Society", service: "Audit & Accounting", rating: 5, review: "Very good service" },
    { name: "Mahendra Ganjekar", society: "Shubh Nil Shivam, Kamothe", service: "Audit & Accounting", rating: 2, review: "Nice" },
    { name: "Darshan Ramesh Lakhimale", society: "Laxmi Nivas Society", service: "Audit & Accounting", rating: 5, review: "Excellent" },
    { name: "Prashant Ingale", society: "Tulip Empire Co-operative Society", service: "Audit & Accounting", rating: 5, review: "Team is very proactive and has a helping approach" },
    { name: "Prema Kadu", society: "Sai Prem Co-op Hsg Society", service: "Property Registration", rating: 5, review: "Excellent" },
    { name: "Sonvi Lad", society: "Five Star Twin CHS Ltd", service: "Legal Service", rating: 5, review: "Good" },
    { name: "Mithun Roy", society: "Kailash Tower, Kamothe", service: "Audit & Accounting", rating: 5, review: "Keep up the good work" },
    { name: "Siddappa Mallikarjun Alegavi", society: "Nalanda Residency CHS", service: "Society Registration", rating: 5, review: "We are satisfied for your work" },
    { name: "Shubhangi Jagannath Lakade", society: "Platinum Lovino, Kamothe", service: "Audit & Accounting", rating: 5, review: "They provide good service" },
    { name: "Sarita Mhatre", society: "Trimurti Heritage", service: "Audit & Accounting", rating: 5, review: "Good service" },
    { name: "Shiv Kishun", society: "Kamothe Trimurthi Heritage", service: "Society Registration", rating: 5, review: "Excellent" },
    { name: "Divakar K Kamath", society: "Nalanda Residency CHS Ltd", service: "Society Accounts Work", rating: 4, review: "Since you engaged in our society's work very recently, we appreciate your prompt action." },
    { name: "Tatyarao Jadhav", society: "Bhagyavanti Residency", service: "Audit & Accounting", rating: 5, review: "Nice 👍" },
    { name: "Sanjay Lad", society: "Atharv Residency CHS Ltd", service: "Audit & Accounting", rating: 5, review: "Shree Associates has been providing reliable and timely services." },
    { name: "Rahul More", society: "Atharv Residency", service: "Audit & Accounting", rating: 5, review: "Cooperative staff & excellent service" },
    { name: "Siddharth Pawar", society: "Commander Hira Siddhi Homes", service: "Society Registration", rating: 5, review: "Shree Associate is a name that reaches out to people through their work." },
    { name: "Pramod Vitthal Jadhav", society: "Sai Vrindavan CHS Ltd", service: "Audit & Accounting", rating: 5, review: "Outstanding" },
    { name: "Suresh Kumar Dhiman", society: "Tharwanis Residency CHS", service: "Conveyance / Deemed Conveyance", rating: 5, review: "This firm is perfect and has knowledge about all procedures." },
    { name: "Paresh Suresh Shirke", society: "Paradise Group", service: "Society Registration", rating: 5, review: "Very knowledgeable about the society laws." },
    { name: "Swapnil Chavan", society: "Dnyandeep Co-op Credit Society", service: "Legal Service", rating: 5, review: "Nice service" },
    { name: "Vishnu Sharma", society: "Anurag Residency", service: "Legal Service", rating: 5, review: "Got full support" },
    { name: "Suraj Jadhav", society: "Ambika Heritage", service: "Society Registration", rating: 5, review: "Trusted service without any failure." },
    { name: "Vitthal Shankar Mane", society: "Gokulvan CHS Ltd", service: "Transfer", rating: 5, review: "Vitthal Mane" },
    { name: "Shashank Anant Devkar", society: "Amrut Kumbh Society", service: "Conveyance / Deemed Conveyance", rating: 5, review: "Very nice service and fast processing" },
    { name: "Roopkumar Makhija", society: "Paradise Group", service: "Amalgamation & Society Registration", rating: 5, review: "Excellent knowledge about laws." },
    { name: "Dr. Jitendra Pawar", society: "Apna Foundation", service: "Legal Service", rating: 5, review: "Best service with commitment." },
    { name: "Rajaram Hadawale", society: "Riddhi Siddhi Shrushti CHS", service: "Audit & Accounting", rating: 5, review: "Very good service" },
    { name: "Dnyandev Mane", society: "Manjulabai Complex CHS", service: "Audit & Accounting", rating: 5, review: "Good services and supportive staff" },
    { name: "Sandeep Malusare", society: "Ambika Heritage", service: "Society Registration", rating: 5, review: "Good Service" },
    { name: "Ashok V. Bingi", society: "Hari Krishna Avenue CHS", service: "Rent Agreement / CIDCO Work", rating: 5, review: "Prompt service" },
    { name: "Sundarrajan", society: "Pooja Co-operative HS Ltd", service: "Property Registration", rating: 5, review: "Gentleman for all correspondence." },
    { name: "Srikanth (Client)", society: "Thane", service: "Property Registration", rating: 5, review: "Gr8 service, supportive." },
    { name: "Dr. Ranjit Ashok Nanaware", society: "Visava CHS Ltd", service: "CIDCO Work", rating: 5, review: "" },
    { name: "Sagar Patil", society: "Best Employees", service: "Property Registration", rating: 5, review: "Good" },
    { name: "Akshay Shinde", society: "Aradhaya Associates", service: "Property Registration", rating: 5, review: "Highly impressed by professionalism." },
    { name: "Satish P Pawade", society: "Sai Siddhi CHS", service: "Legal Service", rating: 5, review: "Excellent Services" },
    { name: "Deepak Vishnu Zanjurne", society: "Sai Bhakti CHS", service: "Committee Formation", rating: 5, review: "Very helpful and supportive" },
    { name: "Yashwant Shitkar", society: "Riddhi Siddhi Paradise CHS", service: "Conveyance / Deemed Conveyance", rating: 4, review: "" },
    { name: "Suhas Hiraji Mhatre", society: "Manish Makrand CHS Ltd", service: "Audit & Accounting", rating: 5, review: "Good Service" },
    { name: "Bethsheba Dineshkumar", society: "Amrutvel CHS", service: "Property Registration", rating: 5, review: "Fast and easy." }
];
